pursuit = "Software and graphics engineer"

# Classes worth checking:
# CS 3520: Racket interpreter
# CS 4230: OpenMP and CUDA parallel computation
# CS 4300: Python AI demos
# CS 4480: Python networking and server simulators
# CS 6640: Image Processing Python scripts
# CS 6320: Computer Vision model notebooks

# List classes in education section

[[sections]]
title = "Education"
priority = 4

[[sections.entries]]
title = "B.S. in Computer Science"
priority = 0
organization = "University of Utah"
summary = "3.82 GPA, dean's list, full-ride merit-based scholarship"
courses = ["Parallel Programming", "Intro to AI", "Computer Networking", "etc."]
time = "Aug 2019 - May 2023"

[[sections.entries]]
title = "M.S. in Computing: Visualization"
priority = 1
organization = "University of Utah"
summary = "3.95 GPA, dean's list"
courses = ["Interactive Graphics", "Virtual Reality", "Computational Geometry", "etc."]
time = "Aug 2023 - Dec 2025"

[[sections.entries]]
title = "Code to Success Bootcamp"
priority = -1
organization = "Bottega with Ken Garff for Good"
summary = "Summer bootcamp for front-end web development with React."
skills = ["React", "Redux"]
time = "2018"

[[sections]]
title = "Projects"
priority = 0

[[sections.entries]]
title = "Prockit"
priority = 0
summary = "Framework for building easy, performant, and modular procedural content generators."
skills = ["Rust", "voxel engines", "API design", "developer tools", "multi-threading"]
time = "2026"

[[sections.entries]]
title = "Scientific Visualizations, Coursework"
priority = -1
summary = "Advanced visualizations for air vortices, maps, and other spatial data."
skills = ["ParaView", "data visualization", "high-dimensional data"]
time = "2024"

[[sections.entries]]
title = "Interactive OpenGL Renderer"
priority = 0
summary = "Shadow mapping, texture render targets, environment map reflections, and more."
skills = ["C++", "OpenGL", "GLSL", "rendering techniques"]
time = "2023"

[[sections.entries]]
title = "Planets on wgpu"
priority = 0
summary = "Generated earth-like planets, rendered and animated in the browser."
skills = ["Rust", "WebAssembly", "WebGPU", "procedural generation", "rendering techniques"]
time = "2023"

[[sections.entries]]
title = "Gesture Tracking in VR"
priority = 0
summary = "Tracking 3D gestures using VR controllers as \"wands\" in a spell-casting VR game."
skills = ["VR", "Unity", "C#", "Gesture Recognition", "Game Development"]
time = "2023"

[[sections]]
title = "Research"
priority = 2

[[sections.entries]]
title = "\"Digital Image Transformations Degrade Gaze Prediction Accuracy\""
link = "https://github.com/soundeffects/transformations_and_gaze_prediction"
priority = -1
summary = "Master's thesis on dataset limitations for gaze prediction machine learning models."
skills = ["Computer vision", "Python", "Pytorch", "statistics", "technical writing"]
time = "2023 - 2025"

[[sections.entries]]
title = "Quantitative Experience Design Lab"
link = "https://qed.games.utah.edu/"
priority = 0
organization = "University of Utah"
summary = "Member, studied automated narrative design and computer vision"
skills = ["Narrative Design", "AI for games", "computer vision", "technical writing"]
time = "2023 - 2025"

[[sections.entries]]
title = "Camacho Lab"
priority = -1
organization = "Brigham Young University"
summary = "Volunteer, propietary file format integrations and documentation for the lab's photonic circuit designer."
skills = ["Python", "Photonic circuits", "technical writing"]
time = "2021"

[[sections]]
title = "Employment"
priority = 3

[[sections.entries]]
title = "Teaching Assistant"
priority = 0
organization = "University of Utah"
courses = ["Intro to Graphics", "Algorithms", "Parallel Programming", "etc."]
skills = ["mentorship", "communication", "management", "collaboration", "conflict resolution"]
time = "Aug 2020 - May 2024"

[[sections.entries]]
title = "Web Development Intern"
priority = 0
organization = "Crescendo Technologies, Inc."
summary = "Browser automation and end-to-end tests for production web apps."
skills = ["Playwright", "Typescript", "Javascript", "React", "full-stack"]
time = "Summer 2023"

[[sections.entries]]
title = "Deployment Intern"
priority = 0
organization = "Verisage Custom Software"
summary = "Updating Django templates and python packages."
skills = ["Python", "Django", "backend systems"]
time = "Fall 2018"
